### PR TITLE
Fix links to pdfs

### PR DESCRIPTION
**Pull request by fp9695253**

### CODE REVIEW

**Comment by charlesreid1** [comment]
Tested this locally to make sure all the links are working okay.

**Comment by charlesreid1** [comment]
Webhooks were using forms and not json. One more try.

**Comment by charlesreid1** [comment]
Okay, Uncle Archie is now running a private-www integration test on all PRs in the `dcppc-workshops` repo!

**Comment by charlesreid1** [comment]
Hot dog! The Uncle Archie update submodules webhook is working too: https://github.com/dcppc/private-www/pull/113

**Comment by raynamharris** [comment]
thatnks!

**Pull request merged**
